config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'student/loginform' => 'student#loginform', as: :student_loginform
  post 'student/login' => 'student#login', as: :student_login
  get 'user/home' => 'userhome#index', as: :user_home
  delete 'student/logout' => 'student#logout', as: :student_logout
  post 'student/student_session_add/:student_id' => 'student#student_session_add', as: :student_session_add

  resources :dailies, only: %i[show create edit update destroy]
  get 'dailies/:student_id/index' => 'dailies#index', as: :dailies_index
  get 'dailies/new/:date' => 'dailies#new', as: :new_daily
  get 'dailies/:id/stamp' => 'dailies#stamp', as: :stamp_daily
  post 'dailies/canvas' => 'dailies#canvas_save', as: :canvas_save
  get 'dailies/:student_id/stamplist' => 'dailies#stamplist', as: :stamplist_daily

  resources :comments, only: [:create]
  resources :student
  devise_for :users
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :dailies
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create]

  def index
    @students = Student.where(user_id: current_user.id)
    session[:student_id] = nil
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.user_id = current_user.id
    if @student.save
      flash[:notice] = 'You have successfully created a student'
      redirect_to '/user/home'
    else
      flash[:alert] = 'Error creating student'
      render 'new'
    end
  end

  def student_session_add
    session[:student_id] = params[:student_id]
    redirect_to dailies_path
  end

  def loginform
    @student = Student.new
  end

  def login
    student_username = Student.find_by(username: params[:username])
    student_password = Student.find_by(password: params[:password])
    # 例外処理
    begin
      if student_username.id == student_password.id
        session[:student_id] = student_username.id
        flash[:notice] = 'ログインに成功しました'
        redirect_to dailies_index_path(current_student.id)
      else
        flash[:alert] = 'ログインに失敗しました'
        redirect_to root_path
      end
    rescue StandardError
      flash[:alert] = 'ログインに失敗しました'
      redirect_to root_path
    end
  end

  def logout
    session[:student_id] = nil
    flash[:notice] = 'ログアウトしました'
    redirect_to student_loginform_path
  end

  private

  def student_params
    params.permit(:username, :password)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate, only: [:index, :new, :create]
  def index
    # トレーナが登録した学生の一覧を表示する
    user = current_user
    @students = user.students
  end

  def new
    @student = Student.new
  end

  def create
    id = random_string(10)
    password = random_string(10)
    user_id = current_user.id
    @student = Student.new(user_id: user_id,student_id: id, student_pass: password)
    if @student.save
      flash[:notice] = "登録が完了しました"
      redirect_to students_path
    else
      render 'new'
    end
  end

  # ランダムな文字列を生成する
  def random_string(n)
    # ランダムな文字列を生成する
    (0...n).map { (65 + rand(26)).chr }.join
  end
end

app/helpers/student_helper.rb
module StudentHelper
  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def authenticate_student?
    unless current_student
      flash[:alert] = 'You must be logged in to access this section'
      redirect_to root_path
    end
  end

  def accsess_denied_student
    if return_current_account_postion == 'student'
      begin
        if Student.find(params[:student_id]).id != session[:student_id]
          flash[:alert] = "You can't access this page"
          redirect_to dailies_index_path(current_student.id)
        end
      rescue StandardError
        flash[:alert] = "You can't access this page"
        redirect_to dailies_index_path(current_student.id)
      end
    end
  end

  def accsess_denied_user
    if return_current_account_postion == 'user'
      begin
        current_user.student.each do |student|
          @denied = true if student == Student.find(params[:student_id])
        end
      rescue StandardError
        @denied = false
      end

      if @denied == false
        flash[:alert] = "You can't access this page"
        redirect_to user_home_path
      end
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper

  # idをセッションに保存する
  def student_login(student)
    session[:student_id] = student.id
    puts("session[:s_id] = #{session[:student_id]}")
  end


  def current_student
    if session[:student_id]
      @current_user ||= Student.find_by(id: 1)
      puts("@current_user: #{@current_user}")
    else
      puts("session[:student_id] is nil")

    end

  end

  def logged_in_student?
    !current_student.nil?
  end

  def current_student?(student)
    student == current_student
  end

  def student_log_out
    session.delete(:student_id)
    @current_student = nil
  end
end

app/views/student/index.html.erb
<%= stylesheet_link_tag "student"%>

<div class="ui centered grid">
<div class="ui  only row">
  <div class="student_list_title">
    <h2>生徒の一覧</h2>
  </div>
</div>
<div class="ui relaxed divided list" style="margin:50px;">

<% @students.each do |s| %>
  <div class="item">
    <i class="large user icon"></i>
    <%= link_to "#{s.username}", dailies_index_path(s.id), data: {"turbolinks" => false}, class:"content" %></li><br>
  </div>
<% end %>

</div>
</div>

app/views/student/loginform.html.erb
<div class="ui centered grid">
  <h2 class="computer only row">生徒用ログイン</h2>
<%= form_with url: student_login_path do |f| %>
  <h3>ID</h3>
  <div class="ui form computer only row">
    <%= f.text_field :username %>
  </div>
  <h3>パスワード</h3>
  <div class="ui form computer only row">
    <%= f.password_field :password %>
  </div>
  <div class="ui computer only row">
    <%= f.submit "ログイン", class: "ui primary button",style: "margin:30px" %>
  </div>
<% end %>
</div>

<%= debug 'test user' %>
<%= debug 'ID example_student_id' %>
<%= debug 'Password example_student_pass' %>

app/views/student/new.html.erb
<div class="ui centered grid">
  <h2 class="computer only row">生徒のアカウント作成</h2>
<%= form_with url: student_index_path do |f| %>
  <h3>ID</h3>
  <div class="ui form computer only row">
    <%= f.text_field :username %>
  </div>
  <h3>パスワード</h3>
  <div class="ui form computer only row">
    <%= f.password_field :password %>
  </div>
  <div class="ui computer only row">
    <%= f.submit "登録", class: "ui button",style: "margin:30px" %>
  </div>
<% end %>
</div>

app/views/student/show.html.erb
<h1>Student#show</h1>
<p>Find me in app/views/student/show.html.erb</p>