config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'student/loginform' => 'student#loginform', as: :student_loginform
  post 'student/login' => 'student#login', as: :student_login
  get 'user/home' => 'userhome#index', as: :user_home
  delete 'student/logout' => 'student#logout', as: :student_logout
  post 'student/student_session_add/:student_id' => 'student#student_session_add', as: :student_session_add

  resources :dailies, only: %i[show create edit update destroy]
  get 'dailies/:student_id/index' => 'dailies#index', as: :dailies_index
  get 'dailies/new/:date' => 'dailies#new', as: :new_daily
  get 'dailies/:id/stamp' => 'dailies#stamp', as: :stamp_daily
  post 'dailies/canvas' => 'dailies#canvas_save', as: :canvas_save
  get 'dailies/:student_id/stamplist' => 'dailies#stamplist', as: :stamplist_daily

  resources :comments, only: [:create]
  resources :student
  devise_for :users
end

app/controllers/userhome_controller.rb
class UserhomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index; end
end

app/helpers/userhome_helper.rb
module UserhomeHelper
end

app/views/userhome/index.html.erb
<div class="ui center grid">
  <div class="ui only row">
    <%= link_to '生徒の一覧', student_index_path,data: {"turbolinks" => false}, class: "ui primary button", style: "margin: 0 auto" %>
  </div>
  <div class="ui only row">
   <%= link_to '生徒の新規登録', new_student_path, class: "ui primary button", style: "margin: 0 auto"%>
  </div>
</div>