config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'student/loginform' => 'student#loginform', as: :student_loginform
  post 'student/login' => 'student#login', as: :student_login
  get 'user/home' => 'userhome#index', as: :user_home
  delete 'student/logout' => 'student#logout', as: :student_logout
  post 'student/student_session_add/:student_id' => 'student#student_session_add', as: :student_session_add

  resources :dailies, only: %i[show create edit update destroy]
  get 'dailies/:student_id/index' => 'dailies#index', as: :dailies_index
  get 'dailies/new/:date' => 'dailies#new', as: :new_daily
  get 'dailies/:id/stamp' => 'dailies#stamp', as: :stamp_daily
  post 'dailies/canvas' => 'dailies#canvas_save', as: :canvas_save
  get 'dailies/:student_id/stamplist' => 'dailies#stamplist', as: :stamplist_daily

  resources :comments, only: [:create]
  resources :student
  devise_for :users
end

app/models/daily.rb
class Daily < ApplicationRecord
  validates :student_id, :day, presence: true
  belongs_to :student
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  require 'securerandom'
  before_action :authenticate_student?, only: %i[new create]
  before_action :authenticate_student_or_user?, only: %i[index show]
  before_action :accsess_denied_student, only: [:index]
  before_action :accsess_denied_user, only: [:index]
  skip_before_action :verify_authenticity_token

  def index
    dailies = Daily.where(student_id: params[:student_id])
    # 同じ日数のデータをまとめる
    @dailies_group = dailies.group_by(&:day)
    # @dailies_groupをkeysでソートする
    @dailies_group = @dailies_group.sort.reverse.to_h
    # keyのみを取り出す
    @days = @dailies_group.keys

    first_bool = true
    tmp_day = ''
    @day_diffs = []

    @days.each do |day|
      if first_bool
        tmp_day = Date.parse(day)
        @day_diffs << 0
        first_bool = false
      else
        # 文字列を日付に変換
        day = Date.parse(day)
        @day_diffs << (day - tmp_day).to_i.abs
        tmp_day = day
      end
    end
  end

  def show
    @daily = Daily.find(params[:id])
    @comments = @daily.comments.order(created_at: :asc)

  end

  def new
    @daily = Daily.new
    @date = params[:date]
  end

  def create
    @daily = Daily.new(daily_params)
    puts params[:date]
    @daily.student_id = current_student.id
    if params[:date].present?
      @daily.day = params[:date]
    else
      day = Time.zone.now.strftime('%Y-%m-%d')
      @daily.day = day
    end

    if @daily.save
      flash[:notice] = 'You have successfully created a daily'
      redirect_to "/dailies/#{current_student.id}/index"
    else
      flash[:alert] = 'Error creating daily'
      render 'new'
    end
  end

  def destroy
    @daily = Daily.find(params[:id])
    @daily.destroy
    redirect_to "/dailies/#{current_student.id}/index"
  end
  

  def stamp
    @daily = Daily.find(params[:id])
  end

  def canvas_save
    @daily = Daily.find(post_get_daily_params[:daily_id])
    @daily.image = post_get_daily_params[:image]
    puts "post_get_daily_params"
    puts post_get_daily_params[:image_name]
    @daily.image_name = post_get_daily_params[:image_name]
    if @daily.save
      redirect_to "/dailies/#{@daily.id}"
    else
      redirect_to "/dailies/#{@daily.id}/stamp"
    end
  end

  def stamplist
    @dailys = Daily.where(student_id: params[:student_id])
    @iamge_name_list = []
    @dailys.each do |daily|
      # daily.image_nameを,で区切って配列にする
      if daily.image_name == nil
        @iamge_name_list.push([]);
      else
        @iamge_name_list.push(daily.image_name.split(","))
      end
    end
    @iamge_name_list
  end

  private

  def daily_params
    params.permit(:context, :image)
  end


  def post_get_daily_params
    params.permit(:daily_id, :image, :image_name)
  end



end

app/controllers/dailys_controller.rb
class DailysController < ApplicationController
  def index
    current_student
  end
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/dailys_helper.rb
module DailysHelper
end

app/views/dailies/_comment_form.html.erb
<form class="ui reply form" data-dashlane-rid="0035803497efb8a4" data-form-type="" action="/comments" method="post">
  <div class="field">
    <textarea data-dashlane-rid="765bf09375905c29" data-form-type="" name="content"></textarea>
  </div>
  <input type="hidden" name="daily_id" value=<%= "#{params[:id]}"%>>
  <input type="hidden" name="position" value=<%= "#{current_user.nil?}"%>>
  <button type="submit" class="ui blue labeled submit icon button">
    <i class="icon edit"></i> 送信
  </button>
</form>

app/views/dailies/index.html.erb
<%= stylesheet_link_tag "dailies"%>
<%= javascript_pack_tag 'dailies/index', defer: true %>


<div class="ui two item menu only row" style="margin-bottom:30px;">
  <a class="item active">一覧</a>
  <%= link_to 'スタンプ', stamplist_daily_path(params[:student_id]), class: "item", data: {"turbolinks" => false} %>
</div>


<div class="ui grid">
<% @nowtime = Time.zone.now.strftime("%Y-%m-%d") %>
<% @latesttime = @dailies_group.take(1).to_h.keys[0] %>
<% if current_user.nil? %>
  <% if !(@nowtime == @latesttime) %>
    <div class="ui form only row">
      <p>投稿がまだありません.今日の登録してください<a href="/dailies/new/<%= @nowtime %>"><i class="add sign icon" style="font-size:2em; "></i></a></p>
    </div>
  <% end %>
<% end %>
<% l=0 %>
<% @dailies_group.each do |dg| %>
  <% if @day_diffs[l] > 0 %>
    <% for i in 1...@day_diffs[l]%>
      <div class="ui form only row">
        <%= Date.parse(dg[0]) + (@day_diffs[l]-i) %>
      </div>
      <div class="images_list">
      </div>
      <% if current_user.nil? %>
      <div class="ui form only row">
        <%= link_to "+", new_daily_path(Date.parse(dg[0]) + (@day_diffs[l]-i)), class: "ui button blue" %>
      </div>
      <% end %>
    <% end %>
  <% end %>

  <div class="images_list ">
    <% l+=1 %>
    <% for i in 0..dg[1].length %>
      <% @day = dg[1][i] %>
      <% if @day.present? %>
        <div class="four wide column">
        <a href="<%= "/dailies/#{@day.id}" %>" >
        <% begin %>
          <%= image_tag @day.image, class: "index_img", style:"margin-top:10px"%>
        <% rescue => e %>
        <% end %>
        </a>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="eight wide column">
  <% if current_user.nil? %>
    <div class="ui form only row">
      <%= link_to "+", new_daily_path(dg[0]), class: "ui button blue" %>
    </div>
  <% end %>
  </div>
  <div class="eight wide column" style="text-align: right;">
  <p style="font-size: 20px; color:gray;">
  <%= dg[0] %>
  </p>
  </div>

<% end %>
</div>

app/views/dailies/new.html.erb
<div class="ui centered grid">
  <h2 class="computer only row">画像を登録する</h2>
  <%= form_with url: dailies_path do |f| %>

    <h3>画像</h3>
    <div class="ui form computer only row">
      <%= f.file_field :image, accept: "image/*"%>
    </div>
    <%= f.hidden_field :date, value: @date %>
    <div class="ui computer only row">
      <%= f.submit "登録", class: "ui button",style: "margin:30px" %>
    </div>
  <% end %>
</div>

app/views/dailies/show.html.erb
<%= javascript_pack_tag 'dailies/show', defer: true %>

<div class="ui grid">



<div class="four column row" style="width:100%">
  <div class="left floated column">
    <%= link_to dailies_index_path(@daily.student.id), data: {"turbolinks" => false}  do %>
      <button class="ui labeled icon button" style="margin: 5px" >
        <i class="left chevron icon"></i>
        戻る
      </button>
    <% end %>
  </div>
  <div class="right floated column">
    <% if !(current_user.nil?) %>
      <%= link_to "/dailies/#{params[:id]}/stamp", data: {"turbolinks" => false} do %>
        <button class="ui right labeled icon button" style="margin: 5px; width: 100%;" >
          <i class="right chevron icon"></i>
          スタンプ
        </button>
      <% end %>
    <% end %>
  </div>
</div>





  <%= image_tag @daily.image, id: "show_img" %>
  <%# 画像へスタンプをつける %>
  <% if current_user.nil? %>
    <%= link_to "投稿を削除する", daily_path(params[:id]), class:"ui negative basic button", style:"margin: 20px;", method: "DELETE"%>
  <% end %>

    <div class="ui only row" id="body-main">
      <div class="ui comments" style="margin: 0 auto; width: 500px;">
        <h3 class="ui dividing header">コメント</h3>
        <% if @comments.empty? %>
          <p>コメントはまだありません</p>
        <% end %>
        <% @comments.each do |comment| %>
          <div class="comment">
            <% if comment.position == 'false' %>
              <a class="avatar">
                <i class="meh user icon" style="font-size:2.5em;" ></i>
              </a>
            <% else %>
              <a class="avatar">
                <i class="user icon" style="font-size:2.5em; color: red;" ></i>

              </a>
            <% end %>
            <div class="content">
              <% if comment.position == 'false' %>
                <a class="author">トレーナー<%= @comment %></a>
              <% else %>
                <a class="author">生徒<%= @comment %></a>
              <% end %>
              <div class="metadata">
                <span class="date"><%= comment.created_at %></span>
              </div>
              <div class="text">
                <%= comment.content %>
              </div>
            </div>
          </div>
        <% end %>
          <%= render 'comment_form' %>
      </div>
    </div>
</div>

app/views/dailies/stamp.html.erb
<meta name="turbolinks-cache-control" content="no-preview">
<%= stylesheet_link_tag "dailies"%>
<%= javascript_pack_tag 'dailies/stamp', defer: true %>

<div id="main-body">
<div id="load_id">
loading...(ロードが長い場合は、このページを再読み込みしてください)
</div>
<canvas id="canvas"></canvas>
<%# 保存する %>
<div class="ui grid">
  <div class="eight wide column">
    <div class="tool_name">
      <p>スタンプのプレビュー</p>
    </div>
    <canvas id="stamp_viewr" width="500px" height="500px"></canvas>
  </div>
  <div class="eight wide column">
    <%# ラジオボタンを追加する %>
    <div class="ui form">
      <div class="grouped fields">
        <div class="tool_name">
          <p>スタンプの形</p>
        </div>

        <select name="stamp" id="stamp-select">
            <option value="">-- 選択してください --</option>
            <option value="stamp_0004_kinshi.png">禁止マーク</option>
            <option value="stamp_0005_kinshi_junkfood.png">ジャンク禁止マーク</option>
            <option value="stamp_0006_kinshi_sweets.png">甘いもの禁止マーク</option>
            <option value="stamp_0007_mark_alcohol_ng.png">アルコール禁止マーク</option>
            <option value="stamp_0008_stamp1.png">まる</option>
            <option value="stamp_0009_stamp2.png">三角</option>
            <option value="stamp_0010_stamp3.png">ばつ</option>
            <option value="stamp_0011_stamp4.png">グッドマーク</option>
            <option value="stamp_0012_video_cooking_man.png">料理系ユーチューバー</option>
        </select>

      </div>
    </div>
    <%# サイズ変更 %>
    <div class="ui form">
      <div class="field">
        <div class="tool_name">
          <p>スタンプのサイズ</p>
        </div>
        <input type="range" name="size" id="stamp_size" min="1" max="100" value="100">
      </div>
    </div>
    <%# カラーピッカー %>
    <div class="ui form" hidden>
      <div class="field">
        <div class="tool_name">
          <p>コメントの色</p>
        </div>
        <input type="color" name="color">
      </div>
    </div>
    <%# テキストエリア %>
    <div class="ui form">
      <div class="field">
        <div class="tool_name">
          <p>コメント</p>
        </div>
        <textarea name="textarea" id="context" width="50px"></textarea>
      </div>
    </div>
    <div class="tool_name">
      <button class="ui primary button save_link">保存する</button>
    </div>
  </div>
</div>
<%# @daily.imageを非表示labelにする %>
<div id="image_path"><%= @daily.image %></div>
</div>

<input id="daily_id" type="hidden" value=<%= @daily.id %>>
<%= image_tag @daily.image, id: "daily_image" %>

<%= form_with url: dailies_path do |f| %>
      <%= f.text_field :context, id: "hide" %>
      <%= f.file_field :image, id: "hide" %>
      <%= f.submit "登録",id: "hide" %>
<% end %>

<style>
  #hide{
    display: none;
  }
  #image_path{
    display: none;
  }
  #stamp_viewr {
    border: 1px solid black;
  }
  #daily_image {
    /* 非表示 */
    display: none;
  }
</style>

app/views/dailies/stamplist.erb
<%= stylesheet_link_tag "dailies"%>
<%= javascript_pack_tag 'dailies/stamplist', defer: true %>

<div class="ui two item menu only row" style="">
  <%= link_to '一覧', dailies_index_path(params[:student_id]), class: "ui brue item", data: {"turbolinks" => false}  %>
  <a class="item active">スタンプ</a>
</div>


<div class="ui form">
  <div class="grouped fields">
    <select name="stamp" id="stamp-select">
        <option value="">-- 選択してください --</option>
        <option value="stamp_0004_kinshi.png">禁止マーク</option>
        <option value="stamp_0005_kinshi_junkfood.png">ジャンク禁止マーク</option>
        <option value="stamp_0006_kinshi_sweets.png">甘いもの禁止マーク</option>
        <option value="stamp_0007_mark_alcohol_ng.png">アルコール禁止マーク</option>
        <option value="stamp_0008_stamp1.png">まる</option>
        <option value="stamp_0009_stamp2.png">三角</option>
        <option value="stamp_0010_stamp3.png">ばつ</option>
        <option value="stamp_0011_stamp4.png">グッドマーク</option>
        <option value="stamp_0012_video_cooking_man.png">料理系ユーチューバー</option>
    </select>
  </div>
</div>
<div class="ui form">
  <% for i in 0...@dailys.length%>
  <% id_tags = "index_img2 " %>
  <% begin %>
    <% @iamge_name_list[i].each do |iamge_name_list|%>
      <% id_tags = id_tags + " " + iamge_name_list %>
    <% end %>
  <% rescue => e%>
  <% end %>
  <a href=<%="/dailies/#{@dailys[i].id}" %> >
    <%= image_tag @dailys[i].image, class: "#{id_tags}", style:"display:none; margin:0 auto; " %>
  </a>
  <% end %>
</div>