config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'student/loginform' => 'student#loginform', as: :student_loginform
  post 'student/login' => 'student#login', as: :student_login
  get 'user/home' => 'userhome#index', as: :user_home
  delete 'student/logout' => 'student#logout', as: :student_logout
  post 'student/student_session_add/:student_id' => 'student#student_session_add', as: :student_session_add

  resources :dailies, only: %i[show create edit update destroy]
  get 'dailies/:student_id/index' => 'dailies#index', as: :dailies_index
  get 'dailies/new/:date' => 'dailies#new', as: :new_daily
  get 'dailies/:id/stamp' => 'dailies#stamp', as: :stamp_daily
  post 'dailies/canvas' => 'dailies#canvas_save', as: :canvas_save
  get 'dailies/:student_id/stamplist' => 'dailies#stamplist', as: :stamplist_daily

  resources :comments, only: [:create]
  resources :student
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 500 }
  belongs_to :daily
end

app/models/daily.rb
class Daily < ApplicationRecord
  validates :student_id, :day, presence: true
  belongs_to :student
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :dailies
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :student
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  require 'securerandom'
  before_action :authenticate_student?, only: %i[new create]
  before_action :authenticate_student_or_user?, only: %i[index show]
  before_action :accsess_denied_student, only: [:index]
  before_action :accsess_denied_user, only: [:index]
  skip_before_action :verify_authenticity_token

  def index
    dailies = Daily.where(student_id: params[:student_id])
    # 同じ日数のデータをまとめる
    @dailies_group = dailies.group_by(&:day)
    # @dailies_groupをkeysでソートする
    @dailies_group = @dailies_group.sort.reverse.to_h
    # keyのみを取り出す
    @days = @dailies_group.keys

    first_bool = true
    tmp_day = ''
    @day_diffs = []

    @days.each do |day|
      if first_bool
        tmp_day = Date.parse(day)
        @day_diffs << 0
        first_bool = false
      else
        # 文字列を日付に変換
        day = Date.parse(day)
        @day_diffs << (day - tmp_day).to_i.abs
        tmp_day = day
      end
    end
  end

  def show
    @daily = Daily.find(params[:id])
    @comments = @daily.comments.order(created_at: :asc)

  end

  def new
    @daily = Daily.new
    @date = params[:date]
  end

  def create
    @daily = Daily.new(daily_params)
    puts params[:date]
    @daily.student_id = current_student.id
    if params[:date].present?
      @daily.day = params[:date]
    else
      day = Time.zone.now.strftime('%Y-%m-%d')
      @daily.day = day
    end

    if @daily.save
      flash[:notice] = 'You have successfully created a daily'
      redirect_to "/dailies/#{current_student.id}/index"
    else
      flash[:alert] = 'Error creating daily'
      render 'new'
    end
  end

  def destroy
    @daily = Daily.find(params[:id])
    @daily.destroy
    redirect_to "/dailies/#{current_student.id}/index"
  end
  

  def stamp
    @daily = Daily.find(params[:id])
  end

  def canvas_save
    @daily = Daily.find(post_get_daily_params[:daily_id])
    @daily.image = post_get_daily_params[:image]
    puts "post_get_daily_params"
    puts post_get_daily_params[:image_name]
    @daily.image_name = post_get_daily_params[:image_name]
    if @daily.save
      redirect_to "/dailies/#{@daily.id}"
    else
      redirect_to "/dailies/#{@daily.id}/stamp"
    end
  end

  def stamplist
    @dailys = Daily.where(student_id: params[:student_id])
    @iamge_name_list = []
    @dailys.each do |daily|
      # daily.image_nameを,で区切って配列にする
      if daily.image_name == nil
        @iamge_name_list.push([]);
      else
        @iamge_name_list.push(daily.image_name.split(","))
      end
    end
    @iamge_name_list
  end

  private

  def daily_params
    params.permit(:context, :image)
  end


  def post_get_daily_params
    params.permit(:daily_id, :image, :image_name)
  end



end

app/controllers/dailys_controller.rb
class DailysController < ApplicationController
  def index
    current_student
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to students_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def change_day_labels(created_at)
    # スペースで分割する
    date_array = created_at.split(' ')
    # 日付を分割する
    # ["2012", "01", "01"]
    date_day_array = date_array[0].split('-')
    # 日付を変換する
    # ["2012", "01", "01"]
    date_day_array = [date_day_array[1], date_day_array[2], date_day_array[0]]
    # 日付を結合する
    # "01/01/2012"
    date_day_array = date_day_array.join('/')
    # 時間を分割する
    # ["01", "01", "00"]
    time_array = date_array[1].split(':')
    # 時間を変換する
    # ["01", "01", "00"]
    time_array = [time_array[0].to_i, time_array[1].to_i]
    # 時間を結合する
    # "01時01分"
    time_array = "#{time_array.join('時')}分"
    # 日付と時間を結合する
    # "01/01/2012 01:01:00"
    [date_day_array, time_array].join(' ')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/dailys_helper.rb
module DailysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # ユーザーがログイン中のユーザーかどうか確認
  def current_user?(user)
    user == current_user
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def authenticate
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to login_path
    end
  end


end

app/helpers/student_helper.rb
module StudentHelper
  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def authenticate_student?
    unless current_student
      flash[:alert] = 'You must be logged in to access this section'
      redirect_to root_path
    end
  end

  def accsess_denied_student
    if return_current_account_postion == 'student'
      begin
        if Student.find(params[:student_id]).id != session[:student_id]
          flash[:alert] = "You can't access this page"
          redirect_to dailies_index_path(current_student.id)
        end
      rescue StandardError
        flash[:alert] = "You can't access this page"
        redirect_to dailies_index_path(current_student.id)
      end
    end
  end

  def accsess_denied_user
    if return_current_account_postion == 'user'
      begin
        current_user.student.each do |student|
          @denied = true if student == Student.find(params[:student_id])
        end
      rescue StandardError
        @denied = false
      end

      if @denied == false
        flash[:alert] = "You can't access this page"
        redirect_to user_home_path
      end
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper

  # idをセッションに保存する
  def student_login(student)
    session[:student_id] = student.id
    puts("session[:s_id] = #{session[:student_id]}")
  end


  def current_student
    if session[:student_id]
      @current_user ||= Student.find_by(id: 1)
      puts("@current_user: #{@current_user}")
    else
      puts("session[:student_id] is nil")

    end

  end

  def logged_in_student?
    !current_student.nil?
  end

  def current_student?(student)
    student == current_student
  end

  def student_log_out
    session.delete(:student_id)
    @current_student = nil
  end
end

app/helpers/students_login_helper.rb
module StudentsLoginHelper
end

app/helpers/userhome_helper.rb
module UserhomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="ui inverted large borderless fluid menu column" id="header_id">
    <% if current_user.nil? and current_student.nil? %>
      <a class="header item" href="/">FoodManager</a>
    <% end %>

    <% if !current_user.nil? %>
      <a class="header item" href="/user/home">FoodManager</a>
    <% end %>

    <% if !current_student.nil? %>
      <%= link_to "FoodManager", "/dailies/#{current_student.id}/index", class: "hearder item", data: {"turbolinks" => false} %>
    <% end %>

    <div class="right menu">
        <div class="ui item">
          <% if current_user.nil? and current_student.nil? %>
            <% if current_user.nil?%>
              <%= link_to "トレーナーログイン", new_user_session_path, style: "margin-right: 20px"%>
            <% end %>
            <% if current_student.nil? %>
              <%= link_to "生徒ログイン", student_loginform_path%>
            <% end %>
          <% end %>

          <% if !current_user.nil? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
          <% end %>
          <% if !current_student.nil? %>
            <%= link_to "ログアウト", student_logout_path, method: :delete%>
          <% end %>
        </div>
    </div>
</div>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
  <% if key == "alert" %>
    <div class="ui message red"><%= value %></div>
  <% elsif key == "notice" %>
    <div class="ui message green"><%= value %></div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>FoodManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>

  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/notice' %>

    <div class="ui container segment">
      <%= yield %>
    </div>
  </body>
</html>